# 层次分析法
层次分析法主要用于解决**评价类问题**.
确定三个问题:
1. 评价的目标是什么
2. 评价的标准是什么
3. 可选的方案有哪些
   
## 基本步骤
* 建立层次结构模型
* 构造判断矩阵
* 一致性检验
* 求权重后评价

## 判断矩阵
判断矩阵是对指标的重要性进行两两比较,得到一个 $n*n$ 的矩阵,矩阵元素 $a_{ij}$ 的意义是,第i个指标相对于第j个指标的重要程度.
![image copy.png](<image copy.png>)
  
## 一致矩阵
一致矩阵可以从一个方面对方案进行打分,最终通过加权得到最终评分.
一致矩阵需要满足 $a_{ij}*a_{jk}=a_{ik}$
对于一致矩阵,具有两个性质:
* A的秩为1,A的唯一非零特征根为n
* A的任一列向量都是对应特征根为n的特征向量
## 一致性检验
一致性检验用于检验矩阵是否满足一致性.
**计算一致性指标**: $CI=\frac{\lambda_{max}-n}{n-1},(其中 \lambda 为矩阵的最大特征根)$ 
$$ CI= \begin{cases} 0,具有完全一致性 \\ 接近0,满意的一致性 \\ 越大 ,一致性越差 \end{cases} $$

而为了衡量CI的大小,引入随机一致性指标RI,构造500个判断矩阵 $A_1,A_2,\dots,A_{500}$ 分别计算 $\lambda _{max}$ ,得到五百个一致性指标,定义一致性指标RI= $\frac{\sum_{i=1}^{500}CI_i}{500}$

---
定义一致性比例 $CR=\frac{CI}{RI}$ 如果 $CR<0.1$ 则认为一致性可以接受,否则需要修正
如果大于0.1:强行往一致性上靠,调整成倍数关系即可

## 算术平均法求权重论文表述
对于一个判断矩阵A,有每一列的权重公式    $w_i=\frac1n \sum_{j=1}^{n} \frac{a_{ij}}{\sum_{k=1}^{n} a_{kj}} \quad (i=1,2,\ldots,n)$ ,然后加起来求算术平均值就可以得到权重
## 几何平均法
* 第一步将矩阵的元素按照行相乘得到一个新的向量
* 第二步将新的向量的每一个分量开n次方
* 第三步对该列向量进行归一化即可得到权重向量
最终的数学表达式是:
$$w_{i} = \frac{\left(\prod_{j=1}^{n} a_{ij}\right)^{\frac{1}{n}}}{\sum_{k=1}^{n}\left(\prod_{j=1}^{n} a_{kj}\right)^{\frac{1}{n}}}, \quad (i=1,2,\ldots, n)$$ 
## 特征值法求权重
计算矩阵A的特征值与特征向量,然后进行一致性检验,通过一致性检验后,取特征向量中最大特征值对应的特征向量再进行归一化,即为权重向量.
 


## 论文表述

1. 先列出**层级结构图**(目标层,决策层,方案层) (图片要出现在论文当中)
  ![alt text](image.png)
2. 构造出**判断矩阵**,判断矩阵需要满足一致性
3. 依照评价指标,对方案进行打分
4. 计算权重,并计算得分
5. 比较得分,得出结果

In [13]:
import numpy as np
import pandas as pd
#np.array是一个函数用于创建数组,将输入的对象(如列表,元组,其他数组等)转换为numpy数组
A=np.array([[1,2,3,5],[1/2,1,1/2,2],[1/3,2,1,2],[1/5,1/2,1/2,1]])
A


array([[1.        , 2.        , 3.        , 5.        ],
       [0.5       , 1.        , 0.5       , 2.        ],
       [0.33333333, 2.        , 1.        , 2.        ],
       [0.2       , 0.5       , 0.5       , 1.        ]])

In [14]:
n=A.shape[0] #获取A的行,1则是获取A的列,shape是获取形状信息
n

4

In [15]:
eig_val,eig_vec = np.linalg.eig(A) #计算特征值和特征向量
print(eig_val)
print("###")
print(eig_vec)

[ 4.11283004+0.j         -0.06510522+0.67976113j -0.06510522-0.67976113j
  0.01738039+0.j        ]
###
[[ 0.84869741+0.j          0.81061718+0.j          0.81061718-0.j
  -0.93329324+0.j        ]
 [ 0.30763892+0.j         -0.18477808-0.292718j   -0.18477808+0.292718j
  -0.07585913+0.j        ]
 [ 0.39621458+0.j         -0.26858914+0.38344901j -0.26858914-0.38344901j
  -0.16238727+0.j        ]
 [ 0.16758584+0.j          0.0623862 -0.00277699j  0.0623862 +0.00277699j
   0.31119046+0.j        ]]


In [16]:
max_eig=max(eig_val) #计算最大特征值
CI=(max_eig-n)/n #计算CI
RI=[0,0.0001,0.52,0.89,1.12,1.26,1.36,1.41,1.46,1.49,1.52,1.54,1.56,1.58,1.59] #RI值
CR=CI/RI[n-1] #计算CR
print("一致性指标CI=",CI)
print("一致性指标CR=",CR)
if CR<0.10:
    print("该矩阵的一致性可以接受")
else:
    print("该矩阵的一致性不可接受")

一致性指标CI= (0.028207509548036747+0j)
一致性指标CR= (0.03169383095285028+0j)
该矩阵的一致性可以接受


# 算术平均法

In [17]:
A=np.array([[1,2,3,5],[1/2,1,1/2,2],[1/3,2,1,2],[1/5,1/2,1/2,1]])
#axis属于参数,计算数组某一个维度上的元素总和.例如axis=0,计算每一列元素的总和;axis=1,计算每一行元素的总和
ASum=np.sum(A,axis=0)

n=A.shape[0]

#归一化,二维数组除以一维数组,得到二维数组
stand_A=A/ASum

# 各列相加到同一行
Asumr=np.sum(stand_A,axis=1)
print(Asumr)

#计算权重
w=Asumr/n
print(w)

[1.95543964 0.72771982 0.92757079 0.38926975]
[0.48885991 0.18192996 0.2318927  0.09731744]


# 几何平均法求权重

In [18]:
A=np.array([[1,2,3,5],[1/2,1,1/2,2],[1/3,2,1,2],[1/5,1/2,1/2,1]])

n=A.shape[0]

prod_A=np.prod(A,axis=1)

prod_n_A=np.power(prod_A,1/n) #求n次方

#归一化

norm_prod_n_A=prod_n_A/np.sum(prod_n_A)

print(norm_prod_n_A)

[0.49492567 0.17782883 0.22724501 0.1000005 ]


# 特征值法求权重

In [19]:
A=np.array([[1,2,3,5],[1/2,1,1/2,2],[1/3,2,1,2],[1/5,1/2,1/2,1]])
n=A.shape[0]
# 求特征值与特征向量
eig_val,eig_vec = np.linalg.eig(A)
# 求最大特征值的索引
index=np.argmax(eig_val)
# 求最大特征值
max_vec=eig_vec[:,index]
# 特征向量归一化
weights=max_vec/np.sum(max_vec)

print(weights)

[0.4933895 +0.j 0.17884562+0.j 0.230339  +0.j 0.09742588+0.j]
