# numpy的使用

In [1]:
# 运算
import numpy as np # type: ignore #
print(np.array([1,2,3])+np.array([4,5,6]))#对应向量的相加
print(np.array([1,2,3])*np.array([4,5,6]))#对应向量的点乘

[5 7 9]
[ 4 10 18]


In [7]:
# 随意改变数组的行列,前提是行列数乘积不变
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr.shape)#(4,3) 4行3列
new_arr=np.reshape(arr,(2,6))#将arr变成2行6列的数组 注意：2*6=4*3,一定要乘积相等
print(new_arr,new_arr.shape)#(2,6)

(4, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)


In [8]:
# 各种处理数据
arr1=np.array([1,2,3])
arr2=np.array([4,5,6]) 
print(np.dot(arr1,arr2))#1*4+2*5+3*6=32 点乘
print("平均值",np.mean(arr))#平均值
print("方差",np.var(arr))#方差
print("标准差",np.std(arr))#标准差
print("最大值",np.max(arr))#最大值
print("最小值",np.min(arr))#最小值
print("中位数",np.median(arr))#中位数\
print("求和",np.sum(arr))#求和
print("排序",np.sort(arr))#排序


32
平均值 6.5
方差 11.916666666666666
标准差 3.452052529534663
最大值 12
最小值 1
中位数 6.5
求和 78
排序 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# 处理数据的保存与导入 生成npy文件
print("保存与导入")
print(arr)
np.save("arr.npy",arr)#保存
arr=np.load("arr.npy")
print(arr)#导入

保存与导入
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
