# topisi分析法

## 基本步骤
* 将原始矩阵正向化 正向化就是把所有的指标类型统一转化成极大型指标
* 正向指标标准化,主要目的是去除量纲的影响,保证不同的评价指标在同一个数量级中,且大小排序不变
* 计算得分并且归一化
  $$S_i=\frac{D_i^-}{D_i^++D_i^-},其中S_i为得分,D_i^+为评价对象与最大值之间的距离,D_i^-评价对象与最小值的距离$$
### 正向化
* 极大型指标:直接保留
* 极小型指标: $\widetilde{x}_i=max-x,\widetilde{x}_i是转化后的指标,max为指标最大值,x为指标值$
* 中间型指标(越接近某一个值最好): $设x_{best}为最优值,{x_i}为一组中间型序列,M=max{|x_i-x_{best}|},\widetilde{x}_i=1-\frac{|x_i-x_{best}|}{M}$
* 区间型指标(在某个区间内最好): 
 $$\{x_i\}为一组区间型序列,最佳区间为[a,b],正向化公式如下:\\ M = max \{a - min\{x_i\}, max\{x_i\} - b\}, \quad \widetilde{x}_i = \begin{cases} 1 - \frac{a - x_i}{M} &  x_i < a \\ 1  &  a \leq x_i \leq b \\ \frac{x_i - b}{M} &  x_i > b \end{cases} $$
 ### 标准化
 假设有n个要评价的对象,m个评价指标构成的正向矩阵如下:
 $$X = \begin{bmatrix} x_{11} & \cdots & x_{1m} \\\ \vdots & \ddots & \vdots \\\ x_{n1} & \cdots & x_{nm} \end{bmatrix}
$$
那么将标准化的矩阵记为Z,则Z的计算公式为:
$$z_{ij} = \frac{x_{ij}}{\sqrt{\sum_{i=1}^{n} x_{ij}^2}},(每一个元素/ \sqrt{其所在列的元素平方和}
$$
### 计算得分并归一化
$$定义最大值  Z^+ = (Z_1^+, Z_2^+, \ldots, Z_m^+) = (max\{z_{11}, z_{21}, \ldots, z_{n1}\}, max \{z_{12}, z_{22}, \ldots, z_{n2}\}, \ldots, max\{z_{1m}, z_{2m}, \ldots, z_{nm}\})\\ 定义最小值 Z^- = (Z_1^-, Z_2^-, \ldots, Z_m^-) = (min\{z_{11}, z_{21}, \ldots, z_{n1}\}, min\{z_{12}, z_{22}, \ldots, z_{n2}\}, \ldots, min\{z_{1m}, z_{2m}, \ldots, z_{nm}\}) \\ 定义第 i (i = 1, 2, \ldots, n) ) 个评价对象与最大值的距离为 \\ D_i^+ = \sqrt{\sum_{j=1}^{m} (Z_j^+ - z_{ij})^2} \\
定义第 i (i = 1, 2, \ldots, n) ) 个评价对象与最小值的距离为 \\ D_i^- = \sqrt{\sum_{j=1}^{m} (Z_j^- - z_{ij})^2} \\
那么我们可以计算出第 i (i = 1, 2, \ldots, n) 个评价对象未归一化的得分:  S_i = \frac{D_i^-}{D_i^+ + D_i^-} \\
很显然 0 \leq S_i \leq 1,且S_i越大,D_i^+越小,即越接近最大值\\ 
我们将得分归一化并换算成百分制: \widetilde{S}_i = \frac{S_i}{\sum_{i=1}^{n} S_i} \times 100
最后将得分归一化并换算成百分制: \widetilde{S}_i = \frac{S_i}{\sum_{i=1}^{n} S_i} \times 100
$$
 

# 代码实现

数据为： 
n=3
m=4
1 2 3 4
9 10 175 120
8 7 164 80
6 3 157 90
165
90 100

In [8]:
import numpy as np # type: ignore
n=int(input()) #参评人数
m=int(input()) #指标个数
print("请输入指标类型,1为极大型,2为极小型,3为中间型,4为区间型")
kind=input().split(" ") #将输入的字符串按空格分开,形成列表
#split用于将字符串分割成子字符串,并返回一个包含这些字符串的列表
print("请输入矩阵")
A=np.zeros(shape=(n,m)) #初始化一个n行m列的矩阵
# zeros参数:shape 一个数字表示一维数组,两个数字表示二维数组; dtype 可选参数,默认为float ;order 数组在内存中的存储顺序 'C'按行存储或'F'按列存储.默认为'C'
for i in range(n):
    A[i]=input().split(" ") #将输入的字符串按空格分开,形成列表
    A[i]=list(map(float,A[i])) #将列表中的元素转换为浮点数
print("请输入矩阵为: \n{}".format(A))

#极小型指标转换为极大型指标的函数
def mintomax(maxx,x):
    x=list(x) #转换成列表
    ans=[[(maxx-e)] for e in x] #这个语法意思就是遍历x每一个值,并且执行一次maxx-e的操作,然后返回一个列表
    return np.array(ans) #返回一个n行1列的矩阵
#中间型指标转换为极大型指标的函数
def midtomax(bestx,x):
    x=list(x)
    h=[abs(e-bestx) for e in x]
    M=max(h)
    ans=[[1-(e/M)] for e in h]
    return np.array(ans)
#区间型指标转换为极大型指标的函数
def regtomax(lowx,highx,x):
    x=list(x)
    M=max(lowx-min(x),max(x)-highx)
    if M==0:
        M=1
    ans=[]
    for i in range(len(x)):
        if x[i]<lowx:
            ans.append([1-(lowx-x[i])/M]) #如果指标值小于下限,则计算其与下限的距离比例
        elif x[i]>highx:
            ans.append([(x[i]-highx)/M]) #如果指标值大于上限,则计算其与上限的距离比例
        else:
            ans.append([1]) #如果指标值在区间内,则直接取1
    return np.array(ans)

# 同一指标类型,将所有指标转化为极大性指标
X=np.zeros(shape=(n,1))
for i in range(m):
    if kind[i]=="1":
        v=np.array(A[:,i])
    elif kind[i]=="2":
        maxA=max(A[:,i])
        v=mintomax(maxA,A[:,i])
    elif kind[i]=="3":
        print("类型三,请输入最优值")
        bestA=float(input())
        v=midtomax(bestA,A[:,i])
    elif kind[i]=="4":
        print("类型四,请输入下限和上限")
        lowA=float(input())
        highA=float(input())
        v=regtomax(lowA,highA,A[:,i])
    if i==0:
        X=v.reshape(-1,1)
        # reshape(-1,1)将v的每一行转换成1列,形成一个新的矩阵,-1为自动识别所需要的行数
    else:
        X=np.hstack((X,v.reshape(-1,1))) #将v的每一行与X的每一行拼接在一起,形成一个新的矩阵
print("同一指标后,矩阵为,\n{}".format(X))

# 标准化
X=X.astype('float') #转换成浮点数
for j in range(m):
    X[:,j]=X[:,j]/np.sqrt(np.sum(X[:,j]**2)) #计算每一列的元素平方和,然后开根号,最后将每一列的元素除以该值
print("标准化后的矩阵为,\n{}".format(X))

# 最大值与最小值距离的计算
x_max=np.max(X,axis=0) #计算每一列的最大值
x_min=np.min(X,axis=0) #计算每一列的最小值
d_z=np.sqrt(np.sum(np.square((X-np.tile(x_max,(n,1)))),axis=1)) #计算每一行与最大值的距离
d_f=np.sqrt(np.sum(np.square((X-np.tile(x_min,(n,1)))),axis=1)) #计算每一行与最小值的距离
print("每个指标最大值是:",x_max)
print("每个指标最小值是:",x_min)
print("d+向量:",d_z)
print("d-向量:",d_f)
# 得分排名
s=d_f/(d_z+d_f) #计算得分
score=100*s/sum(s) #将得分s转换为百分制
for i in range(len(score)):
    print("第{i+1}个评价对象的得分为:{}",score[i]) #打印评分




请输入指标类型,1为极大型,2为极小型,3为中间型,4为区间型
请输入矩阵
请输入矩阵为: 
[[  9.  10. 175. 120.]
 [  8.   7. 164.  80.]
 [  6.   3. 157.  90.]]
类型三,请输入最优值
类型四,请输入下限和上限
同一指标后,矩阵为,
[[9.  0.  0.  1. ]
 [8.  3.  0.9 0.5]
 [6.  7.  0.2 1. ]]
标准化后的矩阵为,
[[0.66896473 0.         0.         0.66666667]
 [0.59463532 0.3939193  0.97618706 0.33333333]
 [0.44597649 0.91914503 0.21693046 0.66666667]]
每个指标最大值是: [0.66896473 0.91914503 0.97618706 0.66666667]
每个指标最小值是: [0.44597649 0.         0.         0.33333333]
d+向量: [1.340809   0.62649664 0.79132442]
d-向量: [0.40104223 1.06311478 1.00149764]
第{i+1}个评价对象的得分为:{} 16.23619091405427
第{i+1}个评价对象的得分为:{} 44.37091892667675
第{i+1}个评价对象的得分为:{} 39.39289015926897
